[project]
name = "bundle-tunnel"
authors = ["@developer"]
description = "Decentralized asset management protocol with comprehensive tracking and verification"
telemetry = false
requirements = []
[contracts.bundle-tunnel]
path = "contracts/bundle-tunnel.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
